platform :ios, '9.0'

target 'MFXTester' do

  # Pods for MFXTester
  pod 'MFXSDK', :path => '../'
  pod 'MFXSDK_AdMob', :path => '../'
  pod 'MFXSDK_MoPub', :path => '../'
  pod 'mopub-ios-sdk', '~> 5.11'
  pod 'Google-Mobile-Ads-SDK', '~> 7.55'
#pod 'MFXSDK', :git => 'https://github.com/mobfox/MFX-iOS-SDK.git', :branch => 'rc/4.0.10'
#pod 'MFXSDK', '4.1.0'

  target 'MFXTesterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
