# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MFXTester' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MFXTester
  pod 'MFXSDK', :path => '../'
#pod 'MFXSDK', :git => 'https://github.com/mobfox/MFX-iOS-SDK.git', :branch => 'rc/4.0.10'
#pod 'MFXSDK', '4.1.0'

  target 'MFXTesterTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
